### ISSUE TITLE
Without an Elastic IP(which intentionally costs the same as the instance at idle), this proxy doesn't really work

### ISSUE THREAD

**Issue by johnseth97** [birjolaxew/aws-minecraft-proxy#13]
Every time you start the instance back up, the IP will be different than the IP baked into package.json

Using this shell command, it is possible to get the IP of a running instance with the instance ID, which stays static.

```
aws --region <region-name> \
ec2 describe-instances \
--filters \
"Name=instance-state-name,Values=running" \
"Name=instance-id,Values=<instance-name> \
--query 'Reservations[*].Instances[*].[PublicIpAddress]' \
--output text
```

Is it possible to use this to dynamically set the IP of the proxy each time a start command is issued?

**Comment by birjj** [comment]
Have you tried using the private IP of the instance? This should remain static even when the instance is shut down, and should be reachable from your proxy instance as long as both are hosted on AWS.

Otherwise I would be open to a PR implementing optional IP getting. As I mentioned in an earlier issue, I'm no longer using this project myself, but if you feel like setting it up I would be happy to merge.

**Comment by johnseth97** [comment]
I have attempted using the private IP of the instance, but the proxy doesn't seem to be able to forward to that(and implementing such would likely incur a lot of extra data charges)

**Comment by birjj** [comment]
As long as you can reach the private IP from your proxy server (i.e. you get a response when running `ping <private-ip>`) then you should be able to forward to it. This is what I did back when developing the project. An elastic IP address should only be needed for your proxy server (or you could use a dynamic DNS service if you want to avoid that cost). 

If you feel that the better solution is to implement dynamic IP getting in this project, then I'd welcome PRs.

**Comment by birjj** [comment]
@desojo Could I get you to test the code in the [`dynamic-host`](https://github.com/birjj/aws-minecraft-proxy/tree/dynamic-host) branch? That code adds support for the `get_host` and `get_port` commands. Your config would then look a little something like:

```json
{
    "minecraft-aws": {
        "target": {
            "port": 25565
        },
        "commands": {
            "start": "aws ec2 start-instances --instance-ids i-0...",
            "shutdown": "aws ec2 stop-instances --instance-ids i-0...",
            "get_host": "aws ec2 describe-instances --instance-ids i-0... --query 'Reservations[*].Instances[*].PublicIpAddress' --output text",
        }
    }
}
```

(the above is entirely untested; adapt as needed. The `get_host` command should only output the IP address of the target, nothing else)

**Comment by birjj** [comment]
Closing as inactive, and likely solvable using an appropriate AWS setup.
